
version: '3'
services:
  myapp:
    container_name: myapp
    restart: always
    build: .
    ports:
      - '4300:4300'
      - '4301:4301'
    links:
      - redis
      - mongo
  mongo:
    container_name: myapp-mongo
    image: 'mongo:4'
  redis:
    container_name: myapp-redis
    image: 'redis:4.0.11'