name: Deployment
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab 
  workflow_dispatch:
  
# The environemnt variables are used from the "DEVELOPMENT" environment
env:
    DEVELOPMENT  

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: QA
    steps:
      - name: deploy
        # ...deployment-specific steps
