name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!
    
  DeployDev:
    name: Deploy to Dev 
    if: github.event_name == 'push'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      APP_NAME: bb2app
      AZURE_CONTAINER_REGISTRY: seagwamaksdevacr
      RESOURCE_GROUP: seagwam-aks-dev-rg
      CLUSTER_NAME: asia-dev-sea-aks
      NAMESPACE: ns-gwam-aw-ifunds-dev
      SECRET: acr-secret
    steps:
      - name: Deploy
        run: echo I am deploying!
    
  DeployQA:
    name: Deploy to QA
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: QA
      url: 'http://test.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 

  DeployPrepod:
    name: Deploy to Prepod 
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: prepod
      url: 'http://test.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
          
  DeployProd:
    name: Deploy to Production 
    needs: [DeployPrepod]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying!
